{{ $ldaps := fromYaml ( include "glauth.ldaps-certs" . ) }}
{{ $api := fromYaml ( include "glauth.api-certs" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "glauth.namePrefix" . }}-ldaps-tls
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "glauth.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ldaps.caCert }}
  tls.crt: {{ $ldaps.clientCert }}
  tls.key: {{ $ldaps.clientKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "glauth.namePrefix" . }}-api-tls
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "glauth.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $api.caCert }}
  tls.crt: {{ $api.clientCert }}
  tls.key: {{ $api.clientKey }}